server:
  port: 9006

spring:
  application:
    # 注册到服务中心后，当前微服务的名字（serviceID）
    name: consumer2

eureka:
  instance:
    # 设置当前微服务在服务中心中的节点名称为 ip:port
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
    # 服务中心的地址
      defaultZone: http://localhost:8761/eureka/
feign:
 hystrix:
  enabled: true